name: BookStore
description: Next gen book store. 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  rxdart: 0.27.2
  http: ^0.13.4
  heroicons: ^0.3.0
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  lottie: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/baner.png
    - assets/images/08.png
    - assets/images/atomichabits.jpg
    - assets/images/pctr.jpg
    - assets/images/johnny.jpg
    - assets/images/nursultan.jfif
    - assets/images/piter.jpeg
    - assets/images/tauekel.jfif
    - assets/images/tom.jpg
    - assets/images/profilewallpaper.jpg
    - assets/users.json
    - assets/images/why.jpg
    - assets/images/today.jpg
    - assets/images/zerotoone.jpg
    - assets/images/book1.jpg
    - assets/images/baner2.jpg
    
  
    
    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
